version: '3.2'

services:
  sql2019-db:
    container_name: ids4nh-sql2019
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Passw0rd1!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
      
  postgresql-db:
    container_name: ids4nh-postgresql
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "Passw0rd1!"
    ports:
      - "5432:5432"
      
  mysql-db:
    container_name: ids4nh-mysql
    image: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd1!"
    ports:
      - "3306:3306"

  adminer:
    container_name: ids4nh-adminer
    image: adminer
    ports:
      - "8080:8080"
